### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by tterranigma** [totallymike/contextPlus#17]
Thank you for this useful addon. Here are some feature ideas that could make users' life even easier.

- It makes sense to add a [page action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) for this addon. If this is implemented, then it would be also great if there was an option to disable the tab context menu entry.
- Maybe it is possible to add shortcuts to the tab context menu entries to switch the tabs to different containers.

**Comment by grahamperrin** [comment]
> Page actions are for actions that are only relevant to particular pages. If your icon should always be available, use a browser action instead.

As I see Context Plus: 

- it _is_, essentially, designed to work with all pages
- where it can't work, that's a response to a page design. 

> A page action is a clickable icon inside the browser's address bar.

If that approach will be taken: please [do not make the icon immovable](https://discourse.mozilla.org/t/add-ons-that-can-not-function-without-taking-space-from-the-location-field-of-firefox/19044?u=grahamperrin) – thanks.

**Comment by totallymike** [comment]
I have to say I'm not too keen on the page action idea. A browser action may be more appropriate. I probably won't get around to adding one immediately, but I'm open to a PR!

**Comment by totallymike** [comment]
Now that the page context menu has the addon, I'm thinking we might not need another button anymore? I'm going to close this for now, but feel free to reopen if I'm totally wrong!
