### ISSUE TITLE
Please add menu items on the context of the page also, not just tabs

### ISSUE THREAD

**Issue by andreicristianpetcu** [totallymike/contextPlus#18]
This would make it a lot easier since the mouse does not need to be moved.
Would you accept a pull request for this? :)

**Comment by seascape** [comment]
Thanks, I was going to suggest similar.

I use Tree Style Tab and normally have the regular tab bar hidden; I have to un-hide it (requires a browser restart) if I want to access the contextPlus functionality.

Three places come to mind:
- Regular context menu
- Toolbar button that can be placed with customize
- (Preferably customizable) keyboard shortcuts

**Comment by andreicristianpetcu** [comment]
I sent a pull request with the fix https://github.com/totallymike/contextPlus/pull/20

@seascape the toolbar button and the keyboard shortcut seem to be different issues. Please create new issues for them.

**Comment by andreicristianpetcu** [comment]
I will use [my own build](https://github.com/andreicristianpetcu/contextPlus/releases/download/0.3.3/context_plus-0.3.3-an.fx.xpi) until this gets merged :D

**Comment by totallymike** [comment]
Merged the PR.  Thanks for adding!

**Comment by andreicristianpetcu** [comment]
UUUhuu.... Landed in AMO :D
