### ISSUE TITLE
Feature suggestion: Open link outside of current container

### ISSUE THREAD

**Issue by seascape** [totallymike/contextPlus#19]
I'm playing with Containers and seeing how they work for me. I created one for Facebook. Only Facebook lives in there.

It seems wrong, then, how when I middle-click FB links that lead to outside sites/stories (to open them in new tabs) the outside sites still end up in the Facebook container. 

It would be nice to be able to open these links in other containers, somehow. 

The most basic implementation might send you to the default/generic container if you click while holding a certain key.

A (much) more complex one might let the user specify rules on how links from various container-ized sites should behave when clicked.

Not sure if this is out of scope or not; just mentioning an immediate concern that arose when experimenting with this stuff.

**Comment by seascape** [comment]
In the link context menu I now notice an option "Open Link in New Container Tab" that on hover opens a submenu with different choices, including No Container. I guess we already have this capability!

**Comment by totallymike** [comment]
:+1: I'll close this unless there's more?
