### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by totallymike** [totallymike/contextPlus#24]
So the name of this addon is pretty dumb. When I first threw it together, I had a few other things I wanted to address about containers (but I can't remember what they were anymore). 

But this addon only does one thing, so the name doesn't make sense.

Should it be renamed? How much would that screw up the ability to find it?

Thoughts?

**Comment by grahamperrin** [comment]
I never thought of it as dumb. _Containers Plus_, maybe? 

> … only does one thing … 

[Switch Container](https://addons.mozilla.org/addon/switch-container/) is comparably focused. Not a bad thing 👍 

I reckon, it's not easy to find a word that conveys the (naturally) limited effect of any such extension/feature. Phrases such as _switch_, _reload_, _copy_, _move_ and _reopen_ may be associated, in minds of users of Firefox (and other reputable browsers), with integrity; **no loss**. 

In contrast: issues such as [loss of content e.g. form field data when copying from one container (context) to another · Issue #15 · totallymike/contextPlus](https://github.com/totallymike/contextPlus/issues/15) and [open tab in different containers with location bar pre-filled · Issue #45 · kesselborn/conex](https://github.com/kesselborn/conex/issues/45) make me hesitate before using such phrases. For what it's worth, recently I find myself veering towards the word _**restart**_ for the losses that occur (or might occur). Flippantly, it's like _**kicking**_ around of content `:-)` …

… but I can't imagine a suitably positive name for the extension that conveys the kicky quality of what's inherent with containers …

HTH

**Comment by gabrielfin** [comment]
I think it should at least have "Containers" in the name.

- Context Containers
- Switch Containers (too bad it's already in use)
- Reload in Container
- Reopen in Container

I don't think there's a name that's gonna make it clear about the privacy issues and the loss of data. I think the best we can do is add a warning on the AMO page. Or maybe show it on first use (as long as there's a nice way to do it that is not an alert dialog...).

**Comment by grahamperrin** [comment]
Yeah. Kicking the ball around …

_Containaway_

_Containerway_ … corny, blegh

_Container shift_

_Recontainer_

…

**Comment by ksesong** [comment]
I believe we should avoid using the *context* terminology, as it can be quite confusing with the *contextual menu*...

Looking at the current menu, I feel something like *sendToContainer* would fit well. The menu item would be similar to the *Send Page to Device*: as *Send Page to Container*. It does give the idea that the new page is different from the current one, and that data loss can be expected in transit.

I think the name should be as functional and unoriginal as possible; the extension does one very simple task (and no more), and the naming should reflect this. (Personally, I would even remove the icon in the menu to make it more integrated.)

**Comment by totallymike** [comment]
These are all good thoughts.  I like the `send` terminology quite a bit.

As an extension name, _Send to Container_ is a bit of a mouthful, unfortunately. 

`<digression>`
Frankly, I'm not sure what I'd want to do about on-page form data and such. I feel like that's _probably_ out of scope for this add-on since there's just about no way to preserve live data for every page everywhere that I can think of.  

The one thing, I think, that bums me out more than possibly losing half-filled-out Form data, is the back button.  When starting this addon, I almost scrapped it all together as not being worth it when I found out I'd lose the back button history!
`</digression>`

Something that evokes sending a tab to a different container is definitely where I'd want to end up.

_Transporter_ might be a good word.  By itself the name is unclaimed, but also not that helpful. 
_Container Transporter_ sounds awful, and implies transportation of the container itself, rather than what goes in it.
_Context Transporter_ sounds better, but has the same problem.

If we accept vague titles, _Transporter_'s not bad. Though I like _Switcheroo_ if we're going that far! :smile:

Maybe something kitschy like _ContaineRelay_? It rolls off the tongue!

Maybe more ideas will come later...

**Comment by grahamperrin** [comment]
> … I like the _send_ terminology quite a bit. …

💯 all things considered, I love it. Something in the future might change my mind but when I first saw it, I loved it. Still do. 

>> … _sendToContainer_ …

I dislike the stringing together of multiple words to form a single word. (I have equal or greater dislike of some of what I strung together! Kicking the ball around.)

> … _Send to Container_ is a bit of a mouthful …

I like it. Not too verbose. Almost identical to what I had in mind immediately after I saw the one-word suggestion. I thought: 

_Send to container_

– lowercase _c_. 

Three words is not excessive. Consider popular extensions, sorted by rating, with _Classic Theme Restorer_ in first place: 

![top rated popular for firefox 2017-10-14](https://user-images.githubusercontent.com/192271/31570563-ef06164c-b07c-11e7-8db4-1a7853cb404d.png)

More generally, it's not unusual to find prominence given to add-ons with multi-word names: 

![add-ons for firefox 2017-10-14](https://user-images.githubusercontent.com/192271/31570575-09eb2970-b07d-11e7-8ece-e752ed792a44.png)

----

> … _Transporter_ …

There's e.g. https://github.com/Pingue/transporter relating to [Transport for London](https://tfl.gov.uk/). I don't imagine a future conflict of interest with that, or with any other transport-oriented technology, but the word _transporter_ **is** relatively generic. 

I prefer something that uses Mozilla's expression – container.

**Comment by grahamperrin** [comment]
## The word 'page'

> … similar to the _Send Page to Device_… new page is different from the current one, and that data loss can be expected in transit. … 

I also like the word _page_, for a variety of reasons. 

For example, I chose the phrase "… restart the page without the container. …" whilst writing about [a screen recording](https://vimeo.com/236201464) that I made two weeks ago; and then [renamed the corresponding bug report](https://gitlab.com/mjanetmars/switch-container/issues/7#note_41981468) to "Switch Container with non-loaded pages".

@ksesong you might find my comment here inconsistent with my down-vote and terse referencing at [Page action (#6) · Issues · MarsCat / switch-container · GitLab](https://gitlab.com/mjanetmars/switch-container/issues/6). Apologies for the terseness etc. … some of my bird's view is difficult to put into writing. 

### Side note

The **Send Tabs** feature of Firefox [arose in chat](http://logs.glob.uno/?c=mozilla%23firefox&s=12+Oct+2017&e=14+Oct+2017#c464130) a couple of days ago. 

----

Not losing sight of the essential question here: 

> # Change name?

Context Plus _is_ fine. The established name has already been promoted in a few high-profile contexts (no pun intended), and so on …
