### ISSUE TITLE
not compatible with ff 56.0.1?

### ISSUE THREAD

**Issue by yhager** [totallymike/contextPlus#26]
ff disabled this add-on after an upgrade to 56.0.1 (64bit, Linux) and in https://addons.mozilla.org/en-US/firefox/addon/context-plus/, it says "not compatible with this version of firefox".

**Comment by totallymike** [comment]
Thanks for submitting.  I don't have a Linux box handy at the moment. Is it still happening?

**Comment by yhager** [comment]
I've tried with a clean profile and it doesn't happen. So clearly something is up with my profile, but I don't know what. I'm guessing it's not a bug in this extension, although it's weird that it was disabled and others are still working. You can close this issue if you have no clue what to do with it. Thanks.

**Comment by grahamperrin** [comment]
@yhager did you 'View Mobile Site' at the time of the reported incompatibility? 

Consider the screen recording at https://matrix.org/_matrix/media/v1/download/matrix.org/OCgXNzenwOtLoYjFmrQYoilX

**Comment by yhager** [comment]
No, it wasn't the mobile site thing. However, your screencast had me go check my user agent, and it was reporting Firefox/50.0. I don't know what caused the extension to show up as incompatible, but that's why I couldn't reinstall it.

I've removed all my extensions, and verified I had no custom settings on the user agent, and it still didn't help. I finally found the config entry 'privacy.resistFingerprinting', I filpped it to false, and got back my normal user agent. 

I was able to re-install this extension afterwards, and life is good. Thanks for your assistance!

**Comment by grahamperrin** [comment]
Thanks!

> … 50.0 …

https://addons.mozilla.org/en-GB/firefox/addon/context-plus/versions/?page=1#version-0.1.0

- 0.1.0beta2 worked _with Firefox for Android 48.0 - *, Firefox 48.0 and later_
- 0.1.0 worked _with Firefox 53.0a1 and later_ …

**Comment by grahamperrin** [comment]
> … finally found the config entry `privacy.resistFingerprinting`, I filpped it to `false`, and got back my normal user agent. …

Nice catch. 

@totallymike re: <https://github.com/pyllyukko/user.js/issues/333#issuecomment-329444447> 

> … new AMO is going to use mozAddonManager web API (which is not affected by resistFingerprinting). This means AMO etc (see below) in future will work … 

– so you might like to close this issue.

**Comment by yhager** [comment]
Thanks!
