### ISSUE TITLE
List of contexts not updated

### ISSUE THREAD

**Issue by chiraag-nataraj** [totallymike/contextPlus#27]
Steps to reproduce:

1. Install Context Plus
2. Create a new container/context through the Multi-Account Containers extension
3. Notice that the new container doesn't appear in the Context Plus context menu.

I'm seeing this issue on Firefox 57 beta 6 on Debian Linux with Context Plus 0.4.2.

[Edit/Clarification] The new container is added to the context menu after a browser restart.

**Comment by totallymike** [comment]
Thanks for submitting. I haven't tested this with Multi-Account Containers yet, but I can see, I think, how this happens.

**Comment by grahamperrin** [comment]
`#thinkbubbles` an underlying bug in Mozilla code? 

(Note to self: something in the Sea Containers area, maybe, and was it specific to a version of Firefox? I'll probably edit and/or delete this comment. @totallymike sorry for the apparently random noise whilst I string together a few things.)

**Comment by totallymike** [comment]
Sorry for the delay in following up on this. I haven't had a chance to investigate thoroughly, but I suspect it has to do with not listening to the contextualIdentities.onCreated event (which seems to only exist in v57). I wonder if MAC has a hook we can tie into to tide us over?

**Comment by psychoslave** [comment]
Do you have an idea about how long this might be before we can hop a fix?

**Comment by totallymike** [comment]
I'll check it out tonight and see what I can do.  Sorry for the delay!
