### ISSUE TITLE
Middle-click to open in new tab

### ISSUE THREAD

**Issue by Mirellanmawl** [totallymike/contextPlus#29]
Middle-clicking (clicking down your mouse-wheel that is) on any element in your browser or on a web site usually opens that element or link in a new tab. Even the browsing history works this way. Therefore, after right-clicking a tab and going to _Move to Context_, middle-clicking any context should duplicate that tab but in the context selected. Besides keeping consistency with the rest of the web browser, I would personally find it very useful.

**Comment by gabrielfin** [comment]
You can currently accomplish that with Ctrl+Click. Unfortunately Firefox doesn't yet allow listening to middle clicks in menu items.
