### ISSUE TITLE
strict_min_version 57.0

### ISSUE THREAD

**Issue by grahamperrin** [totallymike/contextPlus#34]
I see https://github.com/totallymike/contextPlus/commit/ccb26fe9542231d748f1a86a6e919bc8a366f2c3 but 0.5.0 seems to work with Firefox 56.0.2 and Waterfox 56.0.2. 

Please, are you aware of any feature that will not work with 56.x?

**Comment by totallymike** [comment]
I bumped it up when I added a handler to listen for new containers being created. The event that we listen to wasn't added until 57.0. Previously it wouldn't show new containers until the browser was restarted. 

Unless I'm mistaken? Does that currently work in 56?

**Comment by grahamperrin** [comment]
You're correct, that fix is not effective for 0.5.0 with Waterfox 56.0.2. Sorry for the noise!
