### ISSUE TITLE
Have option to make moved to tab the dafult to open with

### ISSUE THREAD

**Issue by rgjones33** [totallymike/contextPlus#38]
Thanks you for the nice add-on this should be part of the default functionality so it is nice you stepped up.
Since you  take the time to move a tab to a Container it would be nice to also make it the default container to open with vs having to do two steps each time.

**Comment by totallymike** [comment]
I believe that functionality is handled best by [Multi Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/). 

Does that suit your needs?

**Comment by totallymike** [comment]
I'm closing this for now. If it's still a going concern, feel free to reopen.
