### ISSUE TITLE
Stops working after last Containers update

### ISSUE THREAD

**Issue by MurzNN** [totallymike/contextPlus#7]
Context Plus stops working after recent Containers extension update (Firefox is still in same 53 version), seems something changed in api?
Menuitem is exists, but do nothing. Can you look and fix this?

**Comment by totallymike** [comment]
Hmm...I just tried it in the latest Nightly, and the current Developer edition, and it seems to do it's job well enough.

if you visit `about:config`, and search for `userContext`, you should see a few options. Is it possible that the following options have been disabled? They should be set as `true`

<img width="834" alt="about_config_and_stops_working_after_last_containers_update_ _issue__7_ _totallymike_contextplus" src="https://cloud.githubusercontent.com/assets/320778/26451858/bdec620c-412b-11e7-933e-88f11f4f7277.png">

Failing that, would you mind visiting `about:debugging`, enabling debugging, and then clicking `debug` under the context plus addon?

*Note that I'm taking these screenshots in Nightly, but you should use the browser in which you're experiencing problems*

<img width="977" alt="debugging_with_firefox_developer_tools" src="https://cloud.githubusercontent.com/assets/320778/26451939/07ce16b8-412c-11e7-8b23-184058698bb3.png">

That UI may look slightly different.  It appears they redesigned it recently.

After clicking the `Debug` button, you should see a popup like this:

<img width="1064" alt="item-0_and_item-0_and_item-0_and_item-0_and_item-0" src="https://cloud.githubusercontent.com/assets/320778/26451991/43a89618-412c-11e7-8986-ec56b2a0c674.png">

What's happening is that a separate instance of Firefox is being launched, and it's asking permission to allow remote debugging on your running instance of Firefox.

Click `OK`, and then you'll get a console running in the addon context.

After you have this open, you can go back and try to use the addon. Could you share a screenshot or a paste of any errors that may show up?

Thanks!

**Comment by MurzNN** [comment]
Both options are enabled in about:config, via debugging I got those error:
```
info.modifiers is undefined  contextPlus.js:37
    <anonymous>
moz-extension://c0e3016a-8e38-4848-94b9-08397115a370/contextPlus.js:37:27
    runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
    runSafeSync resource://gre/modules/ExtensionUtils.jsm:104:37
    runSafe resource://gre/modules/ExtensionCommon.jsm:123:32
    receiveMessage resource://gre/modules/ExtensionChild.jsm:613:49
    _callHandlers/< resource://gre/modules/MessageChannel.jsm:574:17
    _callHandlers resource://gre/modules/MessageChannel.jsm:573:14
    _handleMessage/deferred.promise<
resource://gre/modules/MessageChannel.jsm:637:7
    _handleMessage resource://gre/modules/MessageChannel.jsm:634:24
    bound _handleMessage self-hosted:916:17
    receiveMessage resource://gre/modules/MessageChannel.jsm:165:5
```
FIrefox is 53.0 (64-bit)
Containers extension version is 2.3.0

-- 
Best regards,
Alexey Murz Korepov.
Email, Jabber: murznn@gmail.com

**Comment by MurzNN** [comment]
It works on Firefox Nightly (55) and dev (54), but stops working on Firefox Stable
(53.0+build6-0ubuntu0.16.04.1). Some month ago it works normally on same
system and same Firefox 53 version, so this is strange that it stops
working. Same problem on my other computers with Ubuntu 17.04 and 14.04, also in Windows 10 too.
So the problem is that your extension stops working on Firefox 53 version (in which it works previously), maybe because Containers extension updated and change something.

**Comment by jonathanKingston** [comment]
@MurzNN this might be due to you having "always private mode" enabled perhaps? This has been reported by a few other users. Are you using the test pilot work.

**Comment by MurzNN** [comment]
I don't enable this mode and I can't find where is it located in Firefox settings. I check this now in clean Firefox 53 profile and all works well, so seems there are some conflict with settings or extension. I'll try to find it.

**Comment by jonathanKingston** [comment]
@MurzNN it has a few names as we are moving these options about, however like always clear history and cookies on restart or something like this might cause breakage.

**Comment by totallymike** [comment]
@MurzNN This may be cleared up now.  Firefox 53 doesn't support modifier keys when clicking context menu items.  I pushed an update that checks for the feature before trying to use it, and it should work now.

**Comment by MurzNN** [comment]
Thanks, now it works well!
